1. Create two custom layers in TensorFlow that add two inputs and multiply two inputs
respectively [or any other mathematical operations of your choice(linear or
nonlinear)] Add layer names and other things that are present in other common
layers in TensorFlow. (5pts)

We are creating our own custom layers rather than existing Dense layer,but no trainable parameter created

In [1]:
import tensorflow as tf

# Custom layer for addition
class AddLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(AddLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # No trainable parameters needed for addition
        super(AddLayer, self).build(input_shape)

    def call(self, inputs):
        # Custom forward pass: Element-wise addition
        return tf.reduce_sum(inputs, axis=-1, keepdims=True)

# Custom layer for multiplication
class MultiplyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(MultiplyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # No trainable parameters needed for multiplication
        super(MultiplyLayer, self).build(input_shape)

    def call(self, inputs):
        # Custom forward pass: Element-wise multiplication
        return tf.reduce_prod(inputs, axis=-1, keepdims=True)

# Example usage
input1 = tf.keras.layers.Input(shape=(10,), name='input1')
input2 = tf.keras.layers.Input(shape=(10,), name='input2')

# Adding custom layers
addition_result = AddLayer(name='addition_layer')([input1, input2])
multiplication_result = MultiplyLayer(name='multiplication_layer')([input1, input2])

# Creating a model
model = tf.keras.Model(inputs=[input1, input2], outputs=[addition_result, multiplication_result])

# Displaying the model summary
model.summary()


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input1 (InputLayer)            [(None, 10)]         0           []                               
                                                                                                  
 input2 (InputLayer)            [(None, 10)]         0           []                               
                                                                                                  
 addition_layer (AddLayer)      (2, None, 1)         0           ['input1[0][0]',                 
                                                                  'input2[0][0]']                 
                                                                                                  
 multiplication_layer (Multiply  (2, None, 1)        0           ['input1[0][0]',             

2.Combine these two layers in a third custom layer. Concatenate them or multiply
them etc. (5pts)

Combine layers is just the combination of 2 layers that we performed just before in which wew are adding our own custom layer without training.We are concatenating Add_layer and multiply_layer along a new axis

In [5]:
import tensorflow as tf

class CombineLayers(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(CombineLayers, self).__init__(**kwargs)
        self.add_layer = AddLayer()
        self.multiply_layer = MultiplyLayer()

    def build(self, input_shape):
        # Build the sub-layers
        self.add_layer.build(input_shape)
        self.multiply_layer.build(input_shape)
        super(CombineLayers, self).build(input_shape)

    def call(self, inputs):
        # Custom forward pass: Concatenate the outputs of AddLayer and MultiplyLayer
        addition_result = self.add_layer(inputs)
        multiplication_result = self.multiply_layer(inputs)
        combined_result = tf.concat([addition_result, multiplication_result], axis=-1)
        return combined_result

# Example usage
input1 = tf.keras.layers.Input(shape=(10,), name='input1')
input2 = tf.keras.layers.Input(shape=(10,), name='input2')

# Adding the custom layer that combines the outputs
combine_layer = CombineLayers(name='combine_layer')([input1, input2])

# Creating a model
model = tf.keras.Model(inputs=[input1, input2], outputs=combine_layer)

# Displaying the model summary
model.summary()


Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input1 (InputLayer)            [(None, 10)]         0           []                               
                                                                                                  
 input2 (InputLayer)            [(None, 10)]         0           []                               
                                                                                                  
 combine_layer (CombineLayers)  (2, None, 2)         0           ['input1[0][0]',                 
                                                                  'input2[0][0]']                 
                                                                                                  
Total params: 0
Trainable params: 0
Non-trainable params: 0
________________________________

3. Create a model using these and observe how batch inference works (10 pts)

In [ ]:
Lets build by using Add layer, Multiply layer, Combine layer  inwhich the custom layer that we have created so based on it we are creating amodel

In [6]:
import tensorflow as tf
import numpy as np

# Define the custom layers (AddLayer, MultiplyLayer, CombineLayers)
class AddLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(AddLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        super(AddLayer, self).build(input_shape)

    def call(self, inputs):
        return tf.reduce_sum(inputs, axis=-1, keepdims=True)

class MultiplyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(MultiplyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        super(MultiplyLayer, self).build(input_shape)

    def call(self, inputs):
        return tf.reduce_prod(inputs, axis=-1, keepdims=True)

class CombineLayers(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(CombineLayers, self).__init__(**kwargs)
        self.add_layer = AddLayer()
        self.multiply_layer = MultiplyLayer()

    def build(self, input_shape):
        self.add_layer.build(input_shape)
        self.multiply_layer.build(input_shape)
        super(CombineLayers, self).build(input_shape)

    def call(self, inputs):
        addition_result = self.add_layer(inputs)
        multiplication_result = self.multiply_layer(inputs)
        combined_result = tf.concat([addition_result, multiplication_result], axis=-1)
        return combined_result

# Create model
input_shape = (10,)
input1 = tf.keras.layers.Input(shape=input_shape, name='input1')
input2 = tf.keras.layers.Input(shape=input_shape, name='input2')

# Adding custom layers
addition_result = AddLayer(name='addition_layer')([input1, input2])
multiplication_result = MultiplyLayer(name='multiplication_layer')([input1, input2])
combined_result = CombineLayers(name='combine_layer')([input1, input2])

# Creating a model
model = tf.keras.Model(inputs=[input1, input2], outputs=[addition_result, multiplication_result, combined_result])

# Generate some sample input data for batch inference
num_samples = 5
input_data1 = np.random.rand(num_samples, *input_shape)
input_data2 = np.random.rand(num_samples, *input_shape)

# Perform batch inference
output = model.predict([input_data1, input_data2])

# Display the output
print("Output Shapes:")
for i, output_tensor in enumerate(output):
    print(f"Output {i + 1}: {output_tensor.shape}")

# Displaying the model summary
model.summary()


1/1 [==============================] - 1s 661ms/step
Output Shapes:
Output 1: (2, 5, 1)
Output 2: (2, 5, 1)
Output 3: (2, 5, 2)
Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input1 (InputLayer)            [(None, 10)]         0           []                               
                                                                                                  
 input2 (InputLayer)            [(None, 10)]         0           []                               
                                                                                                  
 addition_layer (AddLayer)      (2, None, 1)         0           ['input1[0][0]',                 
                                                                  'input2[0][0]']                 
                                                               

4. Use a predefined layer in Tensorflow to split an input/image into 4x4 = 16 tiles
(5pts)

4x4 = 16 tiles, it means dividing the image into 16 smaller, non-overlapping patches, each of size 4x4 pixels

In [10]:
import tensorflow as tf

# Define the input shape (e.g., image shape)
input_shape = (224, 224, 3)  # Assuming a 3-channel RGB image

# Create a sample input image
input_image = tf.random.normal(shape=(1, *input_shape))  # Batch size of 1 for simplicity

# Define the parameters for extracting patches
patches_size = (1, 4, 4, 1)  # (batch_size, patch_height, patch_width, channels)
strides = (1, 4, 4, 1)       # (batch_stride, vertical_stride, horizontal_stride, channel_stride)

# Use tf.image.extract_patches to split the input into tiles
tiles = tf.image.extract_patches(images=input_image, sizes=[1, 4, 4, 1], strides=[1, 4, 4, 1], rates=[1, 1, 1, 1], padding='VALID')

# Display the shapes of the input and the extracted tiles
print("Input Image Shape:", input_image.shape)
print("Extracted Tiles Shape:", tiles.shape)


Input Image Shape: (1, 224, 224, 3)
Extracted Tiles Shape: (1, 56, 56, 48)


5. Write a graph data structure in python with random connections between nodes.
(5pts)
Refer to the image below:

In [11]:
class TreeNode:
    def __init__(self, value):
        self.value = value
        self.children = []

    def add_child(self, child_node):
        self.children.append(child_node)

def print_tree(node, level=0):
    print("  " * level + str(node.value))
    for child in node.children:
        print_tree(child, level + 1)

# Creating nodes
node_a = TreeNode("A")
node_b = TreeNode("B")
node_c = TreeNode("C")
node_d = TreeNode("D")
node_e = TreeNode("E")

# Connecting nodes to form a tree
node_a.add_child(node_b)
node_a.add_child(node_c)
node_a.add_child(node_d)
node_b.add_child(node_e)
node_c.add_child(node_e)
node_d.add_child(node_e)

# Printing the tree structure
print_tree(node_a)


A
  B
    E
  C
    E
  D
    E


6. Two part question
a. Do inference in one of the nodes and write any rules (>,<,==) to decide the
next node based on the output (5 pts).

In [12]:
import numpy as np

# Define the nodes
nodes = {
    "node1": {
        "inputs": [],
        "inference": lambda x: np.random.uniform(0, 1),
        "next_node": None,
    },
    "node2": {
        "inputs": ["node1"],
        "inference": lambda x: x[0] > 0.5,
        "next_node": "node3",
    },
    "node3": {
        "inputs": [],
        "inference": lambda x: np.random.randint(1, 5),
        "next_node": None,
    },
}

# Start at the first node
current_node = "node1"

# Perform inference until we reach a terminal node
while nodes[current_node]["next_node"] is not None:
    # Get the output of the current node
    output = nodes[current_node]["inference"]([])

    # Determine the next node based on the output
    next_node = nodes[current_node]["next_node"]
    for input_node, rule in nodes[next_node]["inputs"]:
        if rule == ">":
            if output > nodes[input_node]["inference"]([]):
                current_node = next_node
                break
        elif rule == "<":
            if output < nodes[input_node]["inference"]([]):
                current_node = next_node
                break
        elif rule == "==":
            if output == nodes[input_node]["inference"]([]):
                current_node = next_node
                break

# Print the final output
print(f"Final output: {nodes[current_node]['inference']([])}")

Final output: 0.1559471959607137


In [14]:
import tensorflow as tf
import random

class AddLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(AddLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        super(AddLayer, self).build(input_shape)

    def call(self, inputs):
        return tf.reduce_sum(inputs, axis=-1, keepdims=True)

class MultiplyLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(MultiplyLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        super(MultiplyLayer, self).build(input_shape)

    def call(self, inputs):
        return tf.reduce_prod(inputs, axis=-1, keepdims=True)

class CustomLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(CustomLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        # You can add custom build logic if needed
        super(CustomLayer, self).build(input_shape)

    def call(self, inputs):
        # Example custom logic: Square each element of the input
        return tf.square(inputs)

# Generate random input
random_input = tf.constant(random.randint(1, 100), shape=(1, 5), dtype=tf.float32)

# Test the layers with random input
add_layer = AddLayer()
multiply_layer = MultiplyLayer()
custom_layer = CustomLayer()

add_result = add_layer(random_input)
multiply_result = multiply_layer(random_input)
custom_result = custom_layer(random_input)

print("Random Input:")
print(random_input)

print("\nAddLayer Result:")
print(add_result)

print("\nMultiplyLayer Result:")
print(multiply_result)

print("\nCustomLayer Result:")
print(custom_result)


Random Input:
tf.Tensor([[90. 90. 90. 90. 90.]], shape=(1, 5), dtype=float32)

AddLayer Result:
tf.Tensor([[450.]], shape=(1, 1), dtype=float32)

MultiplyLayer Result:
tf.Tensor([[5.9049e+09]], shape=(1, 1), dtype=float32)

CustomLayer Result:
tf.Tensor([[8100. 8100. 8100. 8100. 8100.]], shape=(1, 5), dtype=float32)
